config/routes.rb
Rails.application.routes.draw do
  # Root route
  root "homepage#index"

  # Define custom routes
  resources :categories
  resources :goals

  # Tasks routes with a custom member route for completing tasks
  resources :tasks do
    member do
      patch :complete  # Mark a task as complete
    end
  end
  
  # Health check endpoint for uptime monitoring
  get "up" => "rails/health#show", as: :rails_health_check

  # Dynamic PWA files (service worker, manifest)
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Devise routes for users (session, registration, omniauth callbacks)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks", # Custom controller for OmniAuth
    sessions: "users/sessions",                   # Custom session controller
    registrations: "users/registrations"          # Custom registration controller
  }

  # Custom route for handling OAuth callback within the Devise scope
  devise_scope :user do
    get '/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'
    get '/auth/failure', to: 'users/omniauth_callbacks#failure'
  end

  # Other routes you may have:
  # get "callback", to: "sessions#callback"  # This is redundant, remove it
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :tasks
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
      end

      def show
        @category = Category.find(params[:id])
      end

      def new
        @category = Category.new
      end

      def create
        @category = Category.new(category_params)
        if @category.save
          redirect_to @category, notice: "Category was successfully created."
        else
          render :new
        end
      end

      def edit
        @category = Category.find(params[:id])
      end

      def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
          redirect_to @category, notice: "Category was successfully updated."
        else
          render :edit
        end
      end

      def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_url, notice: "Category was successfully destroyed."
      end

      private
        def set_category
          @category = Category.find(params[:id])
        end

        def category_params
          params.require(:category).permit(:name, :description)
        end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_with model: @category do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
<br>
  <%= form.submit "Update Category" %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= link_to 'New Category', new_category_path %>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category) %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1 class = "header">New Category</h1>

<%= form_with model: @category do |form| %>

  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
<br>
  <%= form.submit "Create Category" %>
<% end %>

app/views/categories/show.html.erb
<h1 class = header><%= @category.name %></h1>
<h3 class = description><em><%= @category.description %></em></h3>

<%= link_to "Home", root_path %>

<ul>
  <li><%= link_to "Edit", edit_category_path(@category) %></li>
  <li><%= link_to "Destroy", category_path(@category), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>